### ISSUE TITLE
Noto Serif Gujarati: Mispositioned vowel sign

### ISSUE THREAD

**Issue by Etewilak** [notofonts/gujarati#17]
When the sequence U+0AB8 U+0ACD U+0AAB U+0AC1 is entered, the vowel sign (U+0AC1) is misplaced:
![image](https://user-images.githubusercontent.com/55674356/169436859-be036b20-e448-435c-8682-94467e16e655.png)

**Comment by simoncozens** [comment]
Same issue as #3. Now it looks like this:

![shape](https://user-images.githubusercontent.com/106728/214689332-2eca6367-149e-4bba-9271-1828e1456cf5.png)
