### ISSUE TITLE
Noto Serif Gujarati has a vowel mispositioning issue

### ISSUE THREAD

**Issue by Poojan-Joshi** [notofonts/gujarati#18]
### Title 
  NotoSerifGujarati vowel issue

### Font 
  NotoSerifGujarati

### Where the font came from, and when
  Google Fonts website https://fonts.google.com/noto/specimen/Noto+Serif+Gujarati?subset=gujarati

### Issue
The issue with vowel mispositioning

### Character data
This font has issues with words like એજ્યુકેશન, ટ્યુશન (see image, how the 0AC1 ુ GUJARATI VOWEL SIGN U should be positioned)

### Screenshot
![image](https://user-images.githubusercontent.com/107028527/173480211-67ebccc3-6ee7-4f2d-a9ee-854baf323d17.png)

Noto Sans Gujarati does not have this problem
![image](https://user-images.githubusercontent.com/107028527/173480977-7f3fc2cc-50c0-41fb-9fa9-7e9f2aa10092.png)

_Thank you very much for making Noto Fonts :)_

**Comment by simoncozens** [comment]
This was the same issue as #3. It has been fixed in the sources, and we'll do a new release soon.
