### ISSUE TITLE
Noto Serif Gujarati has a Mispositioning issue of ટ્ર

### ISSUE THREAD

**Issue by Poojan-Joshi** [notofonts/gujarati#19]
### Font 
  Noto Serif Gujarati

### Where the font came from
https://fonts.google.com/noto/specimen/Noto+Serif+Gujarati?subset=gujarati

### Issue
Noto Serif Gujarati has a mispositioning of ષ્ટ્ર, does not have an issue with only ટ્ર
(Issue with all varients, Light, Regular, Bold etc) 

### Screenshot
![image](https://user-images.githubusercontent.com/107028527/174006702-f3b2b3ba-e88c-49bf-bcd2-99755e1a51c6.png)

Noto Sans Gujarati does not have this issue
![image](https://user-images.githubusercontent.com/107028527/174006852-b2535ba9-4534-4098-81c4-2c180113e798.png)

**Comment by simoncozens** [comment]
This was also the same issue as #3, has been fixed:

![shape](https://user-images.githubusercontent.com/106728/214689191-31876f8a-8328-4c54-b780-0fb920516568.png)
