### ISSUE TITLE
U+0AFD GUJARATI SIGN THREE-DOT NUKTA ABOVE makes -o and -au non-spacing

### ISSUE THREAD

**Issue by dscorbett** [notofonts/gujarati#32]
### Font
NotoSansGujarati-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/gujarati/releases/tag/NotoSansGujarati-v2.104
Date: 2023-04-06

### Font version
Version 2.104

### Issue
The vowel signs <i>o</i> and <i>au</i> are not spacing in clusters with U+0AFD GUJARATI SIGN THREE-DOT NUKTA ABOVE.

### Character data
ટ૽ોવ
U+0A9F GUJARATI LETTER TTA
U+0AFD GUJARATI SIGN THREE-DOT NUKTA ABOVE
U+0ACB GUJARATI VOWEL SIGN O
U+0AB5 GUJARATI LETTER VA

ટ૽ૌવ
U+0A9F GUJARATI LETTER TTA
U+0AFD GUJARATI SIGN THREE-DOT NUKTA ABOVE
U+0ACC GUJARATI VOWEL SIGN AU
U+0AB5 GUJARATI LETTER VA

ર્ટ૽ોવ
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9F GUJARATI LETTER TTA
U+0AFD GUJARATI SIGN THREE-DOT NUKTA ABOVE
U+0ACB GUJARATI VOWEL SIGN O
U+0AB5 GUJARATI LETTER VA

ર્ટ૽ૌવ
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9F GUJARATI LETTER TTA
U+0AFD GUJARATI SIGN THREE-DOT NUKTA ABOVE
U+0ACC GUJARATI VOWEL SIGN AU
U+0AB5 GUJARATI LETTER VA

### Screenshot
![ટ૽ોવ ટ૽ૌવ ર્ટ૽ોવ ર્ટ૽ૌવ](https://user-images.githubusercontent.com/1124347/230787001-64071f7c-e192-4e32-a612-6a1fef5c08e9.png)

**Comment by simoncozens** [comment]
Fixed in ab08d45

**Comment by dscorbett** [comment]
`uni0AFD_auvowelgujr` is still non-spacing in Noto Sans Gujarati 2.105.
