### ISSUE TITLE
Above-base mark sequences with repha or anusvara are too far to the right

### ISSUE THREAD

**Issue by dscorbett** [notofonts/gujarati#33]
### Font
NotoSansGujarati-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/gujarati/releases/tag/NotoSansGujarati-v2.104
Date: 2023-04-06

### Font version
Version 2.104

### Issue
Combinations of above-base marks with a repha or anusvara have no anchor points and are therefore too far to the right above some bases.

### Character data
ઝૅઝૅંર્ઝૅર્ઝૅં
U+0A9D GUJARATI LETTER JHA
U+0AC5 GUJARATI VOWEL SIGN CANDRA E
U+0A9D GUJARATI LETTER JHA
U+0AC5 GUJARATI VOWEL SIGN CANDRA E
U+0A82 GUJARATI SIGN ANUSVARA
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9D GUJARATI LETTER JHA
U+0AC5 GUJARATI VOWEL SIGN CANDRA E
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9D GUJARATI LETTER JHA
U+0AC5 GUJARATI VOWEL SIGN CANDRA E
U+0A82 GUJARATI SIGN ANUSVARA

ઝેઝેંર્ઝેર્ઝેં
U+0A9D GUJARATI LETTER JHA
U+0AC7 GUJARATI VOWEL SIGN E
U+0A9D GUJARATI LETTER JHA
U+0AC7 GUJARATI VOWEL SIGN E
U+0A82 GUJARATI SIGN ANUSVARA
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9D GUJARATI LETTER JHA
U+0AC7 GUJARATI VOWEL SIGN E
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9D GUJARATI LETTER JHA
U+0AC7 GUJARATI VOWEL SIGN E
U+0A82 GUJARATI SIGN ANUSVARA

ઝૈઝૈંર્ઝૈર્ઝૈં
U+0A9D GUJARATI LETTER JHA
U+0AC8 GUJARATI VOWEL SIGN AI
U+0A9D GUJARATI LETTER JHA
U+0AC8 GUJARATI VOWEL SIGN AI
U+0A82 GUJARATI SIGN ANUSVARA
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9D GUJARATI LETTER JHA
U+0AC8 GUJARATI VOWEL SIGN AI
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9D GUJARATI LETTER JHA
U+0AC8 GUJARATI VOWEL SIGN AI
U+0A82 GUJARATI SIGN ANUSVARA

ર્ઝર્ઝં
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9D GUJARATI LETTER JHA
U+0AB0 GUJARATI LETTER RA
U+0ACD GUJARATI SIGN VIRAMA
U+0A9D GUJARATI LETTER JHA
U+0A82 GUJARATI SIGN ANUSVARA

### Screenshot
![ઝૅઝૅંર્ઝૅર્ઝૅં ઝેઝેંર્ઝેર્ઝેં ઝૈઝૈંર્ઝૈર્ઝૈં ર્ઝર્ઝં](https://user-images.githubusercontent.com/1124347/232130421-4da8aa19-d998-41e6-8e2d-f48b98289629.png)

**Comment by dscorbett** [comment]
`evowelsignanusvaragujr` and `evowelsignrephgujr` are still missing anchor points in Noto Sans Gujarati 2.105.

**Comment by simoncozens** [comment]
Anchors were present, but the glyphs had the wrong category.
